services:
  #######################################
  # Frontend
  #######################################
  frontend:
    container_name: "app-frontend"
    build:
      context: ./frontend
    restart: unless-stopped
    networks:
      - proxynet
  #######################################
  # Backend
  #######################################
  backend:
    container_name: "app-backend"
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
