services:
  #######################################
  # Frontend
  #######################################
  frontend:
    container_name: "${PROJECT_NAME}-frontend"
    build:
      context: .
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    networks:
      - proxynet
  #######################################
  # Backend
  #######################################
  backend:
    container_name: "${PROJECT_NAME}-backend"
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
